services:
  web-tvplus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-tvplus
    ports:
      - "80:80"
    networks:
      - webtvplus
    restart: always

networks:
  webtvplus:
    driver: bridge
