services:
  web-guallinet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-Guallinet
    ports:
      - "8384:80"
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
